version: "3.5"

services:
  database:
    image: postgres:latest
    container_name: cars_database
    ports:
      - "${PGSQL_PORT}:${PGSQL_PORT}"
    environment:
      - POSTGRES_PASSWORD=${PGSQL_USER_PASS}
      - POSTGRES_DB=${PGSQL_DB_NAME}
      - POSTGRES_USER=${PGSQL_USER}
  

  backend:
    build: .
    restart: always
    links:
      - database:${PGSQL_HOST}
    depends_on:
      - database
    ports:
      - "0.0.0.0:3000:3000"
    command: ["./wait-for-it.sh", "database:5432", "--timeout=0", "--", "npm", "run", "prod"]
    env_file: .env
      
